# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
hass_url: https://myhass.duckdns.org/
long_lived_token: thatverylongtokenhere
time_zone: Europe/Warsaw
lat: 45.83
lon: 6.86
alt: 10.8
#solcast_api_key: yoursecretsolcastapikey
#solcast_rooftop_id: yourrooftopid
solar_forecast_kwp: 10
