{{- if .Values.customConfiguration.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emhass.fullname" . }}
data:
  TZ: {{ .Values.timezone }} 
  config_emhass.yaml: |+
{{- if index (.Values.customConfiguration) "config_emhass.yaml" }}
  {{- index (.Values.customConfiguration) "config_emhass.yaml" | nindent 4 -}}
{{- end }}
{{- end }}


